name: mybt
description: my blue print app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  lifecycle: ^0.2.0
  flutter_riverpod: ^0.14.0+3
  freezed_annotation: ^0.14.1

  # network
  dio: ^4.0.0

  # localDB
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  shared_preferences: ^2.0.4

  intl: ^0.17.0
  logger: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_flavorizr: ^2.0.0
  flutter_launcher_icons: ^0.9.0

  freezed: ^0.14.1+3
  json_serializable: ^4.1.1
  hive_generator: ^1.1.0

  mockito: ^5.0.7

  pedantic: ^1.11.0
  build_runner: ^2.0.1

flavorizr:
  app:
    android:
      flavorDimensions: 'flavor-type'
    ios:

  flavors:
    coffee:
      app:
        name: 'コーヒー'
      android:
        applicationId: 'jp.hotdrop.mybt.coffee'
      ios:
        bundleId: 'jp.hotdrop.mybt.coffee'

    tea:
      app:
        name: '紅茶'
      android:
        applicationId: 'jp.hotdrop.mybt.tea'
      ios:
        bundleId: 'jp.hotdrop.mybt.tea'

flutter:
  uses-material-design: true

  assets:
    - assets/app_coffee_images/
    - assets/app_tea_images/
