name: mybt
description: An app that considers the design of an app created with Flutter.

publish_to: 'none'

version: 2.2.0+3

environment:
  sdk: '>=2.17.1 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_riverpod: ^2.0.2
  riverpod_annotation: ^1.0.4

  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0

  dio: ^4.0.6

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.15

  intl: ^0.17.0
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_flavorizr: ^2.1.2
  flutter_launcher_icons: ^0.9.2

  riverpod_generator: ^1.0.4
  freezed: ^2.2.0
  json_serializable: ^6.5.1
  hive_generator: ^1.1.0
  build_runner: ^2.0.1

  mockito: ^5.0.16

  flutter_lints: ^2.0.1

flavorizr:
  app:
    android:
      flavorDimensions: 'flavor-type'
    ios:

  flavors:
    coffee:
      app:
        name: 'コーヒー'
      android:
        applicationId: 'jp.hotdrop.mybt.coffee'
      ios:
        bundleId: 'jp.hotdrop.mybt.coffee'

    tea:
      app:
        name: '紅茶'
      android:
        applicationId: 'jp.hotdrop.mybt.tea'
      ios:
        bundleId: 'jp.hotdrop.mybt.tea'

flutter:
  uses-material-design: true

  assets:
    - assets/app_coffee_images/
    - assets/app_tea_images/
